AGiXT/nextjs

components/systems/agent/tabs/AgentChat.js, components/systems/agent/tabs/AgentInstruct.js
Fix chat and Instruct functionality
=> Fix chat and Instruct functionality

components/systems/agent/AgentPanel.js, components/systems/chain/tabs/ChainAdmin.js, components/systems/chain/tabs/ChainSteps.js, components/systems/prompt/tabs/PromptAdmin.js
=> Fix function execution syntax

components/systems/agent/tabs/AgentConfigure.js
Fix provider list in agent configure page
=> Fix provider list in agent configure page

components/systems/agent/AgentCommand.js, components/systems/provider/ProviderList.js, pages/provider/[provider].js, pages/provider/index.js
Fix providers page to show documentation when clicking on a provider.
=> Fix providers page to show docs

components/systems/agent/AgentCommand.js, components/systems/agent/AgentCommandList.js, components/systems/agent/AgentControl.js, components/systems/agent/tabs/AgentConfigure.js
=> Fix commands and Agent config

components/systems/agent/tabs/AgentConfigure.js
Add extension settings to agent config
=> Add extension settings to agent config

Dockerfile
=> Opt out of NextJS telemetery

components/systems/agent/tabs/AgentConfigure.js
Simplify sliders on agent settings
=> Simplify sliders on agent settings

components/systems/agent/tabs/AgentConfigure.js
Fix agent settings populating and formatting
=> Fix agent settings populating and formatting

components/systems/agent/tabs/AgentConfigure.js
Add consideration for DALLE key
=> Add consideration for DALLE key

components/systems/agent/tabs/AgentConfigure.js
Fix default extension setting value injection
=> Fix default extension setting value injection

components/systems/agent/tabs/AgentConfigure.js
=> Change settings to full width

components/systems/agent/tabs/AgentConfigure.js
=> Add consideration for matching names

components/data/ContentSWR.js, components/systems/agent/AgentPanel.js, components/systems/agent/tabs/AgentConfigure.js, pages/agent/[agent].js
=> Fix update agentConfig

components/systems/agent/AgentList.js, components/systems/agent/AgentPanel.js, components/systems/agent/tabs/AgentConfigure.js, pages/agent/[agent].js, pages/agent/index.js
Fix page changes with agent config
- Switching agents on the agent configuration page had undesired results before, it wasn't updating the fields until you left that page and came back to it.  It is fixed in this PR.
=> Fix page changes with agent config

components/systems/agent/tabs/AgentConfigure.js
Fix useEffect on agent settings
=> Fix useEffect on agent settings

components/systems/agent/AgentList.js
=> Add persistent tab setting

components/systems/agent/tabs/AgentConfigure.js
=> Cleanup replacement logic

components/systems/agent/tabs/AgentConfigure.js, lib/SettingsContext.js, pages/_app.js
=> Store settings instead of pulling every time

components/systems/agent/AgentList.js
=> Set default tab if undefined

components/systems/agent/tabs/AgentChat.js
=> Fix conversation history #46

components/systems/agent/tabs/AgentChat.js, components/systems/agent/tabs/AgentInstruct.js
=> Fix instruct page

components/systems/agent/AgentPanel.js, components/systems/agent/tabs/AgentInstruct.js, components/systems/agent/tabs/AgentPrompt.js
=> Add prompt interaction tab

components/systems/agent/tabs/AgentPrompt.js
=> Only show user input if applicable

components/systems/agent/tabs/AgentChat.js, components/systems/agent/tabs/AgentInstruct.js, components/systems/agent/tabs/AgentPrompt.js
=> Visual improvements for chat area

components/systems/agent/AgentPanel.js, components/systems/memory/MemoryManagement.js
Add memory management page for #10
=> Add memory management page for #10

components/systems/memory/MemoryManagement.js
Add predefined memory collection docs
=> Add predefined memory collection docs

components/systems/conversation/ConversationSelector.js
Add and remove conversations to resolve #62
=> Add and remove conversations to resolve #62

components/systems/conversation/ConversationSelector.js
Fix add conversation dialog box
=> Fix add conversation dialog box

components/systems/agent/AgentList.js, components/systems/train/TrainControl.js, components/systems/train/TrainPanel.js, components/systems/train/tabs/FileTraining.js, components/systems/train/tabs/GithubTraining.js, components/systems/train/tabs/TextTraining.js, components/systems/train/tabs/WebTraining.js, pages/_app.js, pages/train/[train].js, pages/train/index.js
=> Add training pages

components/systems/conversation/CodeBlock.css, components/systems/conversation/CodeBlock.js, components/systems/conversation/ConversationHistory.js
=> add changes easy 

components/systems/chain/ChainArgsEditor.js, components/systems/chain/ChainSelector.js, pages/execution/index.js
=> Start chain execution page

components/systems/agent/AdvancedOptions.js, components/systems/conversation/ConversationHistory.js, components/systems/train/TrainOptions.js, pages/_app.js, pages/settings/index.js
Add right drawer for advanced options
- `AdvancedOptions` component shows when on the interact page.
- `TrainOptions` component shows when on the training page.
- `AgentCommandList` component shows when on the settings page.
=> Add right drawer for advanced options

components/systems/conversation/ConversationHistory.js
=> Fix history bug

components/systems/agent/AdvancedOptions.js, components/systems/agent/AgentPanel.js, components/systems/agent/tabs/AgentPrompt.js, components/systems/chain/ChainArgsEditor.js, components/systems/chain/ChainSelector.js, components/systems/conversation/ConversationHistory.js, pages/_app.js, pages/agent/index.js
=> Add chain execution page

.eslintrc.json, components/systems/agent/AgentList.js, components/systems/chain/ChainList.js, pages/_app.js
When starting server I noticed a few type errors:
1. data.map is not a function solved with first checking if data is an array 
2. Warning: Received the string `false` for the boolean attribute `checked`.  Solved by reassigning darkMode to its boolean value  
3. Error in VScode "Parsing error: Cannot find module 'next/babel'" Solved by adding "next/babel", "next/core-web-vitals" to rc file. 
Resolve the errors in the console and VS code
- restarted server no errors seen in terminal or console related to the type error now
- console logged darkMode to check it's type  
=> Fix type erros

components/systems/agent/tabs/AgentPrompt.js, components/systems/conversation/ConversationHistory.js, components/systems/prompt/PromptAdmin.js, components/systems/prompt/PromptSelector.js
Multiple fixes
- Code block differentiation so that you can download/copy selected ones.
- Fixed prompt execution mode to inject variables properly
- Fixed prompt selector sorting
=> Multiple fixes

components/systems/conversation/ConversationHistory.js
Improve history code blocks
- Moved copy/download into heading of the code block
- Add filename to heading so that the user will know what to expect the file to be called when downloaded.
=> Improve history code blocks

components/systems/agent/tabs/AgentPrompt.js, components/systems/conversation/ConversationHistory.js, pages/_app.js
Add loading to interactions
- Agent will say "Let me think about that for a moment.  Please wait..." between responses.
- This message disappears when the agent responds.
=> Add loading to interactions

components/systems/agent/tabs/AgentPrompt.js, components/systems/prompt/PromptSelector.js
=> Disable buttons while loading

components/systems/conversation/ConversationHistory.js
=> Render images in chat

components/data/MenuSWR.js, components/systems/agent/AgentCommand.js, components/systems/chain/ChainList.js, components/systems/chain/step_types/StepTypeCommand.js, components/systems/chain/step_types/StepTypePrompt.js, components/systems/chain/tabs/ChainSteps.js, components/systems/chain/tabs/partial/ChainStep.js, components/systems/prompt/PromptAdmin.js, components/systems/provider/ProviderList.js, pages/_app.js
Added propTypes for proper type checking
Added to _app: 
```
App.propTypes = {
Component: PropTypes.elementType.isRequired,
pageProps: PropTypes.object.isRequired,
dark: PropTypes.bool.isRequired,
};
```
Removed from _app:
```
if (dark === 'true' ) {
setDarkMode(true);
} else if (dark === 'false') {
setDarkMode = false;
}
```
Removed in getInitialProps: `const dark = getCookie("dark", ctx);`
Refactored with simply: 
```
return { 
dark: true,
pageProps: {},
};
```
- Ensures that the props supplied to app are of the right type 
- And no need for the check and reassignment
- Also added descriptions on console logs for added quality of life
Solves the issue of the wrong data type for the `dark` prop
Checked errors logs 
=> Add propTypes and descriptions for logs

components/systems/agent/tabs/AgentPrompt.js
=> Change send button

components/systems/agent/tabs/AgentPrompt.js, components/systems/prompt/PromptAdmin.js, package-lock.json, package.json
- Add new prompt category dialog
- Update SDK
=> Add new prompt category dialog

components/systems/chain/tabs/ChainSteps.js, components/systems/chain/tabs/partial/ChainStep.js
=> Chain UI improvements

components/systems/chain/ChainArgs.js, components/systems/chain/ChainArgsEditor.js, components/systems/chain/tabs/ChainSteps.js, components/systems/chain/tabs/partial/ChainStep.js
=> Almost there

components/systems/agent/AdvancedOptions.js, pages/_app.js
=> Fix margins

components/systems/agent/AdvancedOptions.js, components/systems/chain/tabs/partial/ChainStep.js
=> Improve chain management ui

.github/workflows/code_style_check.yml
=> Remove cd to frontend folder

Dockerfile, package-lock.json, package.json
=> Update to Node 18.8

components/systems/chain/tabs/ChainAdmin.js, pages/_app.js
Improve chain admin page, Add Page Titles
=> Improve chain admin page, Add Page Titles

components/menu/MainMenu.js, components/systems/agent/AgentPanel.js, components/systems/agent/tabs/AgentConfigure.js, components/systems/chain/ChainPanel.js, components/systems/train/TrainPanel.js, components/systems/train/tabs/ArxivTraining.js, pages/_app.js, pages/new/agent.js, pages/new/chain.js
UI improvements on training and settings pages
=> UI improvements on training and settings pages

components/systems/chain/tabs/ChainSteps.js, components/systems/chain/tabs/partial/ChainStep.js
=> Add args to chain step update

components/menu/MainMenu.js, pages/_app.js
=> Fix menu selection colors

pages/_app.js
Improve drawer interactions
- Drawers properly adjust the top bar and content area when opened or closed on both sides.  This includes retaining the dark mode toggle.
=> Improve drawer interactions

pages/_app.js
=> Modify top bar color

pages/_app.js
=> Remove drawer heading

pages/_app.js
Fix drawer interactions on chain and prompt pages
=> Fix drawer interactions on chain and prompt pages

components/data/MarkdownBlock.js, components/systems/conversation/ConversationHistory.js
Migrate to MarkdownBlock for chat history
=> Migrate to MarkdownBlock for chat history

components/menu/MainMenu.js, pages/_app.js, styles/globals.css
=> Add home button

components/systems/agent/AgentPanel.js, components/systems/agent/tabs/AgentPrompt.js
=> Persist conversation between tabs

components/data/MarkdownBlock.js, components/systems/conversation/ConversationHistory.js, pages/index.js
=> Cleanup code

pages/_app.js
=> Fix margin on right drawer

pages/_app.js
=> Fix max width of content area

components/systems/agent/tabs/AgentPrompt.js, components/systems/command/AudioRecorder.js
=> Add audio to text component

components/data/MarkdownBlock.js, components/systems/settings/AgentConfigure.js, styles/globals.css
=> Add anchor links to Markdown

components/systems/agent/AgentPanel.js, components/systems/train/TrainPanel.js
=> Fix tab wrapping

components/systems/agent/AgentPanel.js, components/systems/train/TrainPanel.js
=> Fix underlining selected tab

components/systems/agent/tabs/AgentPrompt.js, components/systems/conversation/ConversationSelector.js
Add export conversation
- Resolves #86
=> Add export conversation

components/systems/chain/ChainPanel.js, components/systems/chain/tabs/ChainAdmin.js, components/systems/chain/tabs/ChainSteps.js
=> Add export chain

pages/new/agent.js
Add import agent
- Resolves #75
=> Add import agent

pages/new/chain.js
Add chain import
- Resolves #76
=> Add chain import

components/systems/conversation/ConversationSelector.js, package-lock.json, package.json
=> Add import conversation

components/menu/MainMenu.js
Fix change from new to agent pages
=> Fix change from new to agent pages

components/systems/chain/tabs/ChainSteps.js, components/systems/chain/tabs/partial/ChainStep.js, components/systems/prompt/PromptSelector.js
=> Fix duplicate fields and input proper values

components/systems/agent/AgentCommandList.js, components/systems/chain/ChainPanel.js, components/systems/chain/tabs/ChainSteps.js, components/systems/chain/tabs/partial/ChainStep.js, components/systems/command/CommandSelector.js, lib/SettingsContext.js, package-lock.json, package.json, pages/_app.js
=> Switch to get all providers

components/systems/agent/AgentCommandList.js, components/systems/chain/ChainPanel.js, components/systems/chain/tabs/ChainSteps.js, components/systems/chain/tabs/partial/ChainStep.js, components/systems/command/CommandSelector.js, lib/SettingsContext.js, package-lock.json, package.json, pages/_app.js
=> Revert "Switch to get all providers"

components/systems/chain/tabs/ChainSteps.js, components/systems/chain/tabs/partial/ChainStep.js, components/systems/command/CommandSelector.js, lib/SettingsContext.js, package.json, pages/_app.js
=> Speed improvements

lib/SettingsContext.js
=> Use one api call for provider settings

components/systems/chain/tabs/ChainSteps.js, lib/SettingsContext.js, pages/_app.js
Performance on promptCategories
=> Performance on promptCategories

components/systems/prompt/PromptSelector.js, package.json
=> Remove duplicate fields

components/systems/train/tabs/MemoryManagement.js, package.json
=> Add wipe memories button

components/systems/agent/AgentCommand.js, components/systems/agent/AgentCommandList.js, package.json, pages/_app.js
=> Fix slow command toggle

components/systems/settings/SettingsPanel.js, components/systems/settings/tabs/AgentAdmin.js, components/systems/settings/tabs/AgentConfigure.js, pages/agent/index.js, pages/settings/index.js
=> Add tabs to agent settings

components/systems/chain/ChainPanel.js
=> Clean up chain panel tabs
